### ISSUE TITLE
NullPointerException when placing Spawner in world

### ISSUE THREAD

**Issue by Roissica** [DeveloperRic/CustomShop#1]
[Server thread/ERROR]: Could not pass event BlockPlaceEvent to CustomShop v2.1

org.bukkit.event.EventException

```
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.ItemStack.placeItem(ItemStack.java:162) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:534) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]

at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Caused by: java.lang.NullPointerException

```
at com.rictacius.customShop.Shops.onPlaceSpawner(Shops.java:237) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

... 18 more
```

[Server thread/ERROR]: Could not pass event BlockPlaceEvent to CustomShop v2.1

org.bukkit.event.EventException

```
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.ItemStack.placeItem(ItemStack.java:162) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:534) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]

at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

Caused by: java.lang.NullPointerException

```
at com.rictacius.customShop.Shops.onPlaceSpawner(Shops.java:237) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]

... 18 more
```

**Comment by DeveloperRic** [comment]
Ahh, It's an issue with spawner lores. If a spawner did not have any lore that error would pop up. Thank's for reporting the error, I have fixed it and the update will be live within the next 24 hours.
