### ISSUE TITLE
Error during enabling attempt

### ISSUE THREAD

**Issue by ReadZead** [DeveloperRic/CustomShop#2]
HI, please help me, I really want to use this plugin it looks awesome and it would be perfect for my server

5:18:32] [Server thread/INFO]: [0;35;1m[CustomShop] [0;33;1mRegistering Config....[m
[15:18:32] [Server thread/INFO]: [0;35;1m[CustomShop] [0;33;1mRegistering Commands....[m
[15:18:32] [Server thread/INFO]: [0;35;1m[CustomShop] [0;35;1mCommands successfuly registered![m
[15:18:32] [Server thread/INFO]: [0;35;1m[CustomShop] [0;33;1mRegistering Events....[m
[15:18:32] [Server thread/ERROR]: Error occurred while enabling CustomShop v1.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/NBTBase
	at com.rictacius.customShop.Main.registerEvents(Main.java:81) ~[?:?]
	at com.rictacius.customShop.Main.onEnable(Main.java:35) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:410) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:376) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:331) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:261) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.NBTBase
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-PaperSpigot-07ff818-0a645a2]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	... 13 more

**Comment by DeveloperRic** [comment]
This error can occur when you have updated CustomShop without restarting your server. Try restarting your server first, and if the problem persists download the latest version manually from spigot.

**Comment by ReadZead** [comment]
I tried doing everything, installed it with the server closed, and downloaded it from the spigot page but still get the same error

**Comment by ReadZead** [comment]
is the 1.8 version only for the 1.8 or for the whole 1.8?

**Comment by DeveloperRic** [comment]
You might not have the plugin Vault installed. A download link for vault is on the spigot page. You must also download the corresponding version for your server. If your server is running 1.9 download the 1.9 version, same goes for other versions.

**Comment by ReadZead** [comment]
I do have vault, I have the latest version of it

**Comment by DeveloperRic** [comment]
Copy your server's log into Pastebin and send the link. This is an unusual bug, and shouldn't happen under normal circumstances. I'd also like to see what version of Spigot you;re running.

**Comment by ReadZead** [comment]
sure give me one second

**Comment by ReadZead** [comment]
here it is 

http://pastebin.com/dBPKXwzL

**Comment by DeveloperRic** [comment]
Unfortunately, I cannot accept this bug for two reasons. One, because you are running an unsupported mod (Paper Spigot).

> This server is running CraftBukkit version git-PaperSpigot-07ff818-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

And two, you are running this mod in offline mode.

> ***\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

If you would like CustomShop to run on your server, download the source and modify it to run on Paper Spigot.

**Comment by ReadZead** [comment]
where can I download the source?

**Comment by DeveloperRic** [comment]
Right on here :smile: GitHub - if you didn't already know - is a way to share code. Simply click on view code and download the zip. You can then import it into your project and make the modifications you'd like. Please note you must follow the license strictly.

**Comment by ReadZead** [comment]
okay thanks :)

**Comment by DeveloperRic** [comment]
Is that all?

**Comment by ReadZead** [comment]
can you send me a link to where I can find it because I'm not practical with github

**Comment by DeveloperRic** [comment]
![image](https://cloud.githubusercontent.com/assets/10460075/20465810/4aa36a7a-af5e-11e6-86d5-f17f566d1b31.png)

**Comment by ReadZead** [comment]
oh that was easy lol and okay I'll read everything and making sure I won't break any rule that is in the license

**Comment by DeveloperRic** [comment]
Anything else? I want to close this thread

**Comment by ReadZead** [comment]
nope that's all, thanks a lot for the help :)

**Comment by DeveloperRic** [comment]
Alright. Don't hesitate to post any other bugs you encounter (as long as is it from an original Custom Shop version and running on a supported Spigot version, more info is on the plugin page) :smiley:
