### ISSUE TITLE
Error while updating config

### ISSUE THREAD

**Issue by realiis** [DeveloperRic/CustomShop#23]
I put the .jar file into the plugins folder and started the server, then I saw this error in the logs:

```
[Server thread/ERROR]: Error occurred while enabling CustomShop v3.0.0 (Is it up to date?)
java.lang.RuntimeException: Failed to load CustomShop: Fatal error while updating config!
        at com.rictacius.customShop.Main.updateConfig(Main.java:63) ~[CustomShop.jar:?]
        at com.rictacius.customShop.Main.registerConfig(Main.java:50) ~[CustomShop.jar:?]
        at com.rictacius.customShop.Main.onEnable(Main.java:41) ~[CustomShop.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1427]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1427]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1427]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1427]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:734) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[patched_1.17.1.jar:git-Purpur-1427]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1427]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: com.rictacius.customShop.config.migration.MigrationException: Files from a previous migration attempt (.migration-v2-to-v3) exist. Please check that those files aren't needed, then delete them
        at com.rictacius.customShop.config.migration.Migration.createMigrationFolder(Migration.java:85) ~[CustomShop.jar:?]
        at com.rictacius.customShop.config.migration.Migration.createOutputFolder(Migration.java:75) ~[CustomShop.jar:?]
        at com.rictacius.customShop.config.migration.Migration.migrate(Migration.java:41) ~[CustomShop.jar:?]
        at com.rictacius.customShop.Main.updateConfig(Main.java:61) ~[CustomShop.jar:?]
        ... 12 more
```

Server version: 1.17.1 Purpur
Plugins: EssentialsX, nbtapi, luckperms, vault

**Comment by DeveloperRic** [comment]
Hello, the error means that there is already a migration from v2 to v3 taking place & CustomShop doesn't want to corrupt those files.

Usually, you should never see this error unless you restarted your server before CustomShop could finish the initial migration.

Try checking that ".migration-v2-to-v3" isn't needed anymore, then delete it and restart your server.

Note there is a "--pre-migration-backup" folder as well. This folder is a backup of your v2 config files. Check that the backed up configs are the same as the configs in `/plugins/CustomShop` otherwise, it will think you've already migrated to v3.

Lmk if u still have difficulties
