### ISSUE TITLE
Not able to buy anything in the shop

### ISSUE THREAD

**Issue by Unieveth** [DeveloperRic/CustomShop#3]
Whenever someone try's to buy something in the shop it gives this error in console

04/03/2017 17:42:36
17:42:36Could not pass event InventoryClickEvent to CustomShop v1.6.0
Console 04/03/2017 17:42:36
17:42:36org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1840) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at com.rictacius.customShop.Shops.onClick(Shops.java:243) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-96235ab-257d6cd]
... 15 more

**Comment by DeveloperRic** [comment]
Do you have vault installed? Also, what version of Spigot are you running?

**Comment by DeveloperRic** [comment]
The problem seems to be coming from when Custom Shop attempts to access vault. Please ensure you have the latest version of vault installed.

**Comment by DeveloperRic** [comment]
Consider updating to 2.0.0, the bug should be fixed

**Comment by DeveloperRic** [comment]
Please reply within the next 24 hours, or the thread will be locked and closed.

**Comment by Unieveth** [comment]
Sorry for not replying, got busy, but I did finally did get time to try the new update and still spits out this error https://pastebin.com/UdrAMc3A I do have vault installed (https://gyazo.com/3d52e184691d4a40914a157b569f3e7e) and it does work (https://gyazo.com/c7e644c22375388632c4b0408d9f95c0) but just does not work when trying to buy or sell

**Comment by DeveloperRic** [comment]
You do not have an economy plugin installed. The second link [https://gyazo.com/c7e644c22375388632c4b0408d9f95c0] shows that you have a permission and chat link established with vault, but no economy plugin. You will need to hook an economy plugin to vault for any other plugin that uses the Vault Economy system to work.
